name: queschat
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^10.1.0
#  pin_code_fields: ^7.0.0
  persistent_bottom_nav_bar: ^4.0.2
#  bottom_navy_bar: ^6.0.0
  google_nav_bar: ^5.0.6
  cached_network_image: ^3.2.0
  image_picker: ^0.8.0+1
  image_cropper: ^1.4.0
#  video_player: ^2.0.2
  video_player: 2.1.10
  camera: ^0.9.4+17

  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.5
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  permission_handler: ^8.1.6

  mime: ^1.0.0
  file_picker: ^4.1.2
  path: ^1.8.0
#  better_player: ^0.0.81
  better_player: 0.0.76
  webview_flutter: 2.5.0
  video_thumbnail: ^0.4.3
  flutter_image_compress: ^1.1.0

  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  firebase_database: ^8.1.0
  firebase_messaging: ^11.2.3
  firebase_dynamic_links: ^4.0.6

  #  flutter_local_notifications: 5.0.0
  awesome_notifications: ^0.6.21

  flutter_contacts: ^1.1.1+2
  fuzzy: ^0.3.0
  share_plus: ^3.0.4

  path_provider: ^2.0.5
  record: ^3.0.0
  flutter_vibrate: ^1.1.0
#  just_audio: ^0.9.20
  just_audio: 0.9.11
  shimmer: ^2.0.0
  duration_picker: ^1.1.0+1
#  flutter_chat_ui: ^1.5.1
  uuid: ^3.0.5
  open_file: ^3.2.1
  flutter_quill: ^4.0.0
  emoji_picker_flutter: ^1.1.2
  clipboard: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 500
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 700

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
